services:
  - type: web
    name: node-video-chat
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      echo "Build completed successfully"
    startCommand: npm start  # Запускает только сервер, клиент уже собран
    envVars:
      - key: PORT
        value: 9788
      - key: NODE_ENV
        value: production